server:
  port: 8761

eureka:
  instance:
    hostname: eureka
    #ip-address: 118.31.7.229
    ip-address: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    response-cache-update-interval-ms: 3000
    eviction-interval-timer-in-ms: 3000