exam:
  version: 1
  data-center-id: 2
  machine-id: 1

spring:
  application:
    name: user
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/exam?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  redis:
    database: 8
    host: localhost
    port: 6379
    password:
  # 日志配置
  logging:
    level:
      # 打印MyBatis SQL日志
      exam.demo.moduleuser.mapper: debug
      # 打印JDBC日志
      java.sql: debug
      # 打印MyBatis框架日志
      org.apache.ibatis: debug
      # 打印事务日志
      org.springframework.jdbc: debug
server:
  #port: ${random.int[10000,65535]}
  servlet:
    context-path: /user
  port: 8775
eureka:
  client:
    service-url:
      # defaultZone: http://118.31.7.229:8761/eureka
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: false
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5

#    prefer-ip-address: true
#    # 这个是本服务的ip和端口
#    #ip-address: 118.31.7.229
#    ip-address: 192.168.1.102
#    non-secure-port: 8775
ribbon:
  ReadTimeout: 2000

mybatis-plus:
  mapper-locations: classpath:exam/demo/moduleuser/mapper/xml/*.xml,classpath*:exam/demo/moduleuser/mapper/xml/*.xml
  type-aliases-package: exam.demo.moduleuser.pojo.model
