exam:
  version: 1
  data-center-id: 2
  machine-id: 1

spring:
  application:
    name: user
  #  redis:
  #    database: 8
  #    host: 118.31.7.229
  #    port: 6379
  #    password: xym123
  #  datasource:
  #    url: jdbc:mysql://rm-bp1vt89u1y7x0x9t61o.mysql.rds.aliyuncs.com:3306/user?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&useAffectedRows=true
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    username: exam
  #    password: xymXYM@123
  #    hikari:
  #      max-lifetime: 30000
  #      minimum-idle: 3
  #      maximum-pool-size: 10
  #      connection-test-query: SELECT 1
  datasource:
    url: jdbc:mysql://localhost:3306/exam?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  redis:
    database: 8
    host: localhost
    port: 6379
    password: xym123
server:
  #port: ${random.int[10000,65535]}
  servlet:
    context-path: /user
  port: 8775
eureka:
  client:
    service-url:
      # defaultZone: http://118.31.7.229:8761/eureka
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: false
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5

#    prefer-ip-address: true
#    # 这个是本服务的ip和端口
#    #ip-address: 118.31.7.229
#    ip-address: 192.168.1.102
#    non-secure-port: 8775
ribbon:
  ReadTimeout: 2000
