server:
  port: 8766
eureka:
  instance:
    prefer-ip-address: false
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
  #    prefer-ip-address: true
  #    ip-address: 192.168.1.103
  #    non-secure-port: 8766
  client:
    serviceUrl:
      #      defaultZone: http://118.31.7.229:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exam?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: gateway
  redis:
    database: 8
    host: localhost
    port: 6379
    password:
  # 日志配置
  logging:
    level:
      # 打印JDBC日志
      java.sql: debug
  cloud:
    gateway:
      ################################
      # 配置允许跨域请求
      ################################
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
      discovery:
        locator:
          enabled: true
      #    路由定义
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - name: Retry
              args:
                retries: 5
                statuses: BAD_GATEWAY

            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"

        - id: baseinfo
          uri: http://localhost:8083
          predicates:
            - Path=/baseinfo/**
          filters:
            - name: Retry
              args:
                retries: 5
                statuses: BAD_GATEWAY
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"

        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
          filters:
            - name: Retry
              args:
                retries: 5
                statuses: BAD_GATEWAY
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"

        - id: paper
          uri: http://localhost:10050/paper
          predicates:
            - Path=/paper/**
          filters:
            - name: Retry
              args:
                retries: 5
                statuses: BAD_GATEWAY
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"

        - id: exam
          uri: lb://exam
          predicates:
            - Path=/exam/**
          filters:
            - name: Retry
              args:
                retries: 5
                statuses: BAD_GATEWAY
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"
      httpclient:
        response-timeout: 5000
    loadbalancer:
      cache:
        ttl: 5s
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive




org:
  my:
    jwt:
      #跳过认证的路由
      skipAuthUrls:
        - /auth/login
        - /auth/getInfo
        - /auth/getMenu
        - /auth/logout
        - /user/login/logout
        - /baseinfo/subjectType/form
        - /baseinfo/category/info
        - /baseinfo/category/tree
        - /baseinfo/dictionary/value
        - /baseinfo/subject/answer
        - /baseinfo/subjectType/form
        - /baseinfo/category/info
        - /baseinfo/category/tree
        - /baseinfo/dictionary/value
        - /baseinfo/subject/query
        - /baseinfo/combExamConfig/query
        - /baseinfo/combExamConfig/queryItem
        - /user/org/form
        - /user/company/list
        - /user/company/form
        - /user/department/tree
        - /user/department/level
        - /user/department/form
        - /user/resource/list
        - /user/resource/form
        - /user/resource/all
        - /user/role/list
        - /user/usermanagement/exist
        - /user/role/form
        - /user/role/allocResource
        - /user/role/userForm
        - /user/role/resourceForm
        - /user/resource/list
        - /user/position/options
        - /user/position/form
        - /user/systemparam/form
        - /user/usermanagement/list
        - /user/usermanagement/options
        - /user/usermanagement/form
        - /user/department/parent
        - /user/usermanagement/role
        - /paper/template/query
        - /paper/maintain/query
        - /paper/create/normalGen
        - /exam/exampublishrecord/paperInfo
        - /exam/exampublishrecord/userInfo
        - /bes/exam/exampublishrecord/userInfo
        - /bes/exam/grade/markingPaper
        - /bes/exam/dopaper/getPaper
        - /bes/exam/grade/getPaperAnswer
      ############################################
      #   有效时长
      #     单位：d:天、h:小时、m:分钟、s:秒
      ###########################################
      effective-time: 1m
exam:
  data-center-id: 5
  machine-id: 1
  version: 1
